version: '3.1'

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: economist
      MONGO_USERNAME: admin
      MONGO_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongo-initdb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-mongo-init.js:ro
  economist-scraping:
    container_name: economist-scraping
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_HOST=db
    ports:
      - 3000:3000
    depends_on:
      - db
